apiVersion: v1
kind: Pod
metadata:
  name: redis-0-pod
  labels:
    name: redis-0-pod
    env: test
spec:
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    command:
      - redis-server
      - "--protected-mode no"
      - "--bind 0.0.0.0"
      - "--maxmemory 200mb"
      - "--maxmemory-policy allkeys-lru"
    resources:
      limits:
        cpu: "0.25"
        memory: 256Mi
      requests:
        cpu: "0.1"
        memory: 256Mi
      requests:
  nodeSelector:
    invoker-index: "0"

---

apiVersion: v1
kind: Pod
metadata:
  name: redis-1-pod
  labels:
    name: redis-1-pod
    env: test
spec:
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    command:
      - redis-server
      - "--protected-mode no"
      - "--bind 0.0.0.0"
      - "--maxmemory 200mb"
      - "--maxmemory-policy allkeys-lru"
    resources:
      limits:
        cpu: "0.25"
        memory: 256Mi
      requests:
        cpu: "0.1"
        memory: 256Mi
  nodeSelector:
  nodeSelector:
    invoker-index: "1"

---

apiVersion: v1
kind: Pod
metadata:
  name: redis-2-pod
  labels:
    name: redis-2-pod
    env: test
spec:
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    command:
      - redis-server
      - "--protected-mode no"
      - "--bind 0.0.0.0"
      - "--maxmemory 200mb"
      - "--maxmemory-policy allkeys-lru"
    resources:
      limits:
        cpu: "0.25"
        memory: 256Mi
      requests:
        cpu: "0.1"
        memory: 256Mi
  nodeSelector:
  nodeSelector:
    invoker-index: "2"

---

apiVersion: v1
kind: Service
metadata:
  name: redis-0-node
spec:
  selector:
    name: redis-0-pod
  ports:
  - protocol: TCP
    port: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-1-node
spec:
  selector:
    name: redis-1-pod
  ports:
  - protocol: TCP
    port: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-2-node
spec:
  selector:
    name: redis-2-pod
  ports:
  - protocol: TCP
    port: 6379